/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VeniceEvalRouteImport } from './routes/venice-eval'
import { Route as VaultlineRouteImport } from './routes/vaultline'
import { Route as ToolOnboardingRouteImport } from './routes/tool-onboarding'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SdkRouteImport } from './routes/sdk'
import { Route as RelayerRouteImport } from './routes/relayer'
import { Route as QuerylineRouteImport } from './routes/queryline'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as PaymentLabRouteImport } from './routes/payment-lab'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CliRouteImport } from './routes/cli'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AgentDemoRouteImport } from './routes/agent-demo'
import { Route as AgentClearanceRouteImport } from './routes/agent-clearance'
import { Route as A2aLabRouteImport } from './routes/a2a-lab'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as VaultlineSplatRouteImport } from './routes/vaultline.$'
import { Route as ToolsIdRouteImport } from './routes/tools.$id'
import { Route as QuerylineSplatRouteImport } from './routes/queryline.$'
import { Route as ApiRegistryRouteImport } from './routes/api.registry'
import { Route as ApiStoryApiIndexRouteImport } from './routes/api.story-api.index'
import { Route as ApiStoryApiStatusRouteImport } from './routes/api.story-api.status'
import { Route as ApiStoryApiSplatRouteImport } from './routes/api.story-api.$'
import { Route as ApiStorachaStatusRouteImport } from './routes/api.storacha.status'
import { Route as ApiStorachaDelegationRouteImport } from './routes/api.storacha.delegation'
import { Route as ApiRegistryStatusRouteImport } from './routes/api.registry.status'
import { Route as ApiIpfsStatusRouteImport } from './routes/api.ipfs.status'
import { Route as ApiIpfsPinRouteImport } from './routes/api.ipfs.pin'
import { Route as ApiAutomataQuoteRouteImport } from './routes/api.automata.quote'
import { Route as ApiIpfsGetCidRouteImport } from './routes/api.ipfs.get.$cid'

const VeniceEvalRoute = VeniceEvalRouteImport.update({
  id: '/venice-eval',
  path: '/venice-eval',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultlineRoute = VaultlineRouteImport.update({
  id: '/vaultline',
  path: '/vaultline',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolOnboardingRoute = ToolOnboardingRouteImport.update({
  id: '/tool-onboarding',
  path: '/tool-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SdkRoute = SdkRouteImport.update({
  id: '/sdk',
  path: '/sdk',
  getParentRoute: () => rootRouteImport,
} as any)
const RelayerRoute = RelayerRouteImport.update({
  id: '/relayer',
  path: '/relayer',
  getParentRoute: () => rootRouteImport,
} as any)
const QuerylineRoute = QuerylineRouteImport.update({
  id: '/queryline',
  path: '/queryline',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentLabRoute = PaymentLabRouteImport.update({
  id: '/payment-lab',
  path: '/payment-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDemoRoute = AgentDemoRouteImport.update({
  id: '/agent-demo',
  path: '/agent-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentClearanceRoute = AgentClearanceRouteImport.update({
  id: '/agent-clearance',
  path: '/agent-clearance',
  getParentRoute: () => rootRouteImport,
} as any)
const A2aLabRoute = A2aLabRouteImport.update({
  id: '/a2a-lab',
  path: '/a2a-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultlineSplatRoute = VaultlineSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => VaultlineRoute,
} as any)
const ToolsIdRoute = ToolsIdRouteImport.update({
  id: '/tools/$id',
  path: '/tools/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuerylineSplatRoute = QuerylineSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => QuerylineRoute,
} as any)
const ApiRegistryRoute = ApiRegistryRouteImport.update({
  id: '/api/registry',
  path: '/api/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoryApiIndexRoute = ApiStoryApiIndexRouteImport.update({
  id: '/api/story-api/',
  path: '/api/story-api/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoryApiStatusRoute = ApiStoryApiStatusRouteImport.update({
  id: '/api/story-api/status',
  path: '/api/story-api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoryApiSplatRoute = ApiStoryApiSplatRouteImport.update({
  id: '/api/story-api/$',
  path: '/api/story-api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorachaStatusRoute = ApiStorachaStatusRouteImport.update({
  id: '/api/storacha/status',
  path: '/api/storacha/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorachaDelegationRoute = ApiStorachaDelegationRouteImport.update({
  id: '/api/storacha/delegation',
  path: '/api/storacha/delegation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistryStatusRoute = ApiRegistryStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiRegistryRoute,
} as any)
const ApiIpfsStatusRoute = ApiIpfsStatusRouteImport.update({
  id: '/api/ipfs/status',
  path: '/api/ipfs/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIpfsPinRoute = ApiIpfsPinRouteImport.update({
  id: '/api/ipfs/pin',
  path: '/api/ipfs/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutomataQuoteRoute = ApiAutomataQuoteRouteImport.update({
  id: '/api/automata/quote',
  path: '/api/automata/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIpfsGetCidRoute = ApiIpfsGetCidRouteImport.update({
  id: '/api/ipfs/get/$cid',
  path: '/api/ipfs/get/$cid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a2a-lab': typeof A2aLabRoute
  '/agent-clearance': typeof AgentClearanceRoute
  '/agent-demo': typeof AgentDemoRoute
  '/audit': typeof AuditRoute
  '/cli': typeof CliRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/payment-lab': typeof PaymentLabRoute
  '/permissions': typeof PermissionsRoute
  '/queryline': typeof QuerylineRouteWithChildren
  '/relayer': typeof RelayerRoute
  '/sdk': typeof SdkRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/tool-onboarding': typeof ToolOnboardingRoute
  '/vaultline': typeof VaultlineRouteWithChildren
  '/venice-eval': typeof VeniceEvalRoute
  '/api/registry': typeof ApiRegistryRouteWithChildren
  '/queryline/$': typeof QuerylineSplatRoute
  '/tools/$id': typeof ToolsIdRoute
  '/vaultline/$': typeof VaultlineSplatRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/automata/quote': typeof ApiAutomataQuoteRoute
  '/api/ipfs/pin': typeof ApiIpfsPinRoute
  '/api/ipfs/status': typeof ApiIpfsStatusRoute
  '/api/registry/status': typeof ApiRegistryStatusRoute
  '/api/storacha/delegation': typeof ApiStorachaDelegationRoute
  '/api/storacha/status': typeof ApiStorachaStatusRoute
  '/api/story-api/$': typeof ApiStoryApiSplatRoute
  '/api/story-api/status': typeof ApiStoryApiStatusRoute
  '/api/story-api/': typeof ApiStoryApiIndexRoute
  '/api/ipfs/get/$cid': typeof ApiIpfsGetCidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a2a-lab': typeof A2aLabRoute
  '/agent-clearance': typeof AgentClearanceRoute
  '/agent-demo': typeof AgentDemoRoute
  '/audit': typeof AuditRoute
  '/cli': typeof CliRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/payment-lab': typeof PaymentLabRoute
  '/permissions': typeof PermissionsRoute
  '/queryline': typeof QuerylineRouteWithChildren
  '/relayer': typeof RelayerRoute
  '/sdk': typeof SdkRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/tool-onboarding': typeof ToolOnboardingRoute
  '/vaultline': typeof VaultlineRouteWithChildren
  '/venice-eval': typeof VeniceEvalRoute
  '/api/registry': typeof ApiRegistryRouteWithChildren
  '/queryline/$': typeof QuerylineSplatRoute
  '/tools/$id': typeof ToolsIdRoute
  '/vaultline/$': typeof VaultlineSplatRoute
  '/tools': typeof ToolsIndexRoute
  '/api/automata/quote': typeof ApiAutomataQuoteRoute
  '/api/ipfs/pin': typeof ApiIpfsPinRoute
  '/api/ipfs/status': typeof ApiIpfsStatusRoute
  '/api/registry/status': typeof ApiRegistryStatusRoute
  '/api/storacha/delegation': typeof ApiStorachaDelegationRoute
  '/api/storacha/status': typeof ApiStorachaStatusRoute
  '/api/story-api/$': typeof ApiStoryApiSplatRoute
  '/api/story-api/status': typeof ApiStoryApiStatusRoute
  '/api/story-api': typeof ApiStoryApiIndexRoute
  '/api/ipfs/get/$cid': typeof ApiIpfsGetCidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a2a-lab': typeof A2aLabRoute
  '/agent-clearance': typeof AgentClearanceRoute
  '/agent-demo': typeof AgentDemoRoute
  '/audit': typeof AuditRoute
  '/cli': typeof CliRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/payment-lab': typeof PaymentLabRoute
  '/permissions': typeof PermissionsRoute
  '/queryline': typeof QuerylineRouteWithChildren
  '/relayer': typeof RelayerRoute
  '/sdk': typeof SdkRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/tool-onboarding': typeof ToolOnboardingRoute
  '/vaultline': typeof VaultlineRouteWithChildren
  '/venice-eval': typeof VeniceEvalRoute
  '/api/registry': typeof ApiRegistryRouteWithChildren
  '/queryline/$': typeof QuerylineSplatRoute
  '/tools/$id': typeof ToolsIdRoute
  '/vaultline/$': typeof VaultlineSplatRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/automata/quote': typeof ApiAutomataQuoteRoute
  '/api/ipfs/pin': typeof ApiIpfsPinRoute
  '/api/ipfs/status': typeof ApiIpfsStatusRoute
  '/api/registry/status': typeof ApiRegistryStatusRoute
  '/api/storacha/delegation': typeof ApiStorachaDelegationRoute
  '/api/storacha/status': typeof ApiStorachaStatusRoute
  '/api/story-api/$': typeof ApiStoryApiSplatRoute
  '/api/story-api/status': typeof ApiStoryApiStatusRoute
  '/api/story-api/': typeof ApiStoryApiIndexRoute
  '/api/ipfs/get/$cid': typeof ApiIpfsGetCidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a2a-lab'
    | '/agent-clearance'
    | '/agent-demo'
    | '/audit'
    | '/cli'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/mcp'
    | '/payment-lab'
    | '/permissions'
    | '/queryline'
    | '/relayer'
    | '/sdk'
    | '/settings'
    | '/status'
    | '/tool-onboarding'
    | '/vaultline'
    | '/venice-eval'
    | '/api/registry'
    | '/queryline/$'
    | '/tools/$id'
    | '/vaultline/$'
    | '/tools/'
    | '/api/automata/quote'
    | '/api/ipfs/pin'
    | '/api/ipfs/status'
    | '/api/registry/status'
    | '/api/storacha/delegation'
    | '/api/storacha/status'
    | '/api/story-api/$'
    | '/api/story-api/status'
    | '/api/story-api/'
    | '/api/ipfs/get/$cid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a2a-lab'
    | '/agent-clearance'
    | '/agent-demo'
    | '/audit'
    | '/cli'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/mcp'
    | '/payment-lab'
    | '/permissions'
    | '/queryline'
    | '/relayer'
    | '/sdk'
    | '/settings'
    | '/status'
    | '/tool-onboarding'
    | '/vaultline'
    | '/venice-eval'
    | '/api/registry'
    | '/queryline/$'
    | '/tools/$id'
    | '/vaultline/$'
    | '/tools'
    | '/api/automata/quote'
    | '/api/ipfs/pin'
    | '/api/ipfs/status'
    | '/api/registry/status'
    | '/api/storacha/delegation'
    | '/api/storacha/status'
    | '/api/story-api/$'
    | '/api/story-api/status'
    | '/api/story-api'
    | '/api/ipfs/get/$cid'
  id:
    | '__root__'
    | '/'
    | '/a2a-lab'
    | '/agent-clearance'
    | '/agent-demo'
    | '/audit'
    | '/cli'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/mcp'
    | '/payment-lab'
    | '/permissions'
    | '/queryline'
    | '/relayer'
    | '/sdk'
    | '/settings'
    | '/status'
    | '/tool-onboarding'
    | '/vaultline'
    | '/venice-eval'
    | '/api/registry'
    | '/queryline/$'
    | '/tools/$id'
    | '/vaultline/$'
    | '/tools/'
    | '/api/automata/quote'
    | '/api/ipfs/pin'
    | '/api/ipfs/status'
    | '/api/registry/status'
    | '/api/storacha/delegation'
    | '/api/storacha/status'
    | '/api/story-api/$'
    | '/api/story-api/status'
    | '/api/story-api/'
    | '/api/ipfs/get/$cid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  A2aLabRoute: typeof A2aLabRoute
  AgentClearanceRoute: typeof AgentClearanceRoute
  AgentDemoRoute: typeof AgentDemoRoute
  AuditRoute: typeof AuditRoute
  CliRoute: typeof CliRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PaymentLabRoute: typeof PaymentLabRoute
  PermissionsRoute: typeof PermissionsRoute
  QuerylineRoute: typeof QuerylineRouteWithChildren
  RelayerRoute: typeof RelayerRoute
  SdkRoute: typeof SdkRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  ToolOnboardingRoute: typeof ToolOnboardingRoute
  VaultlineRoute: typeof VaultlineRouteWithChildren
  VeniceEvalRoute: typeof VeniceEvalRoute
  ApiRegistryRoute: typeof ApiRegistryRouteWithChildren
  ToolsIdRoute: typeof ToolsIdRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  ApiAutomataQuoteRoute: typeof ApiAutomataQuoteRoute
  ApiIpfsPinRoute: typeof ApiIpfsPinRoute
  ApiIpfsStatusRoute: typeof ApiIpfsStatusRoute
  ApiStorachaDelegationRoute: typeof ApiStorachaDelegationRoute
  ApiStorachaStatusRoute: typeof ApiStorachaStatusRoute
  ApiStoryApiSplatRoute: typeof ApiStoryApiSplatRoute
  ApiStoryApiStatusRoute: typeof ApiStoryApiStatusRoute
  ApiStoryApiIndexRoute: typeof ApiStoryApiIndexRoute
  ApiIpfsGetCidRoute: typeof ApiIpfsGetCidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venice-eval': {
      id: '/venice-eval'
      path: '/venice-eval'
      fullPath: '/venice-eval'
      preLoaderRoute: typeof VeniceEvalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaultline': {
      id: '/vaultline'
      path: '/vaultline'
      fullPath: '/vaultline'
      preLoaderRoute: typeof VaultlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool-onboarding': {
      id: '/tool-onboarding'
      path: '/tool-onboarding'
      fullPath: '/tool-onboarding'
      preLoaderRoute: typeof ToolOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdk': {
      id: '/sdk'
      path: '/sdk'
      fullPath: '/sdk'
      preLoaderRoute: typeof SdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relayer': {
      id: '/relayer'
      path: '/relayer'
      fullPath: '/relayer'
      preLoaderRoute: typeof RelayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queryline': {
      id: '/queryline'
      path: '/queryline'
      fullPath: '/queryline'
      preLoaderRoute: typeof QuerylineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-lab': {
      id: '/payment-lab'
      path: '/payment-lab'
      fullPath: '/payment-lab'
      preLoaderRoute: typeof PaymentLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-demo': {
      id: '/agent-demo'
      path: '/agent-demo'
      fullPath: '/agent-demo'
      preLoaderRoute: typeof AgentDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-clearance': {
      id: '/agent-clearance'
      path: '/agent-clearance'
      fullPath: '/agent-clearance'
      preLoaderRoute: typeof AgentClearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a2a-lab': {
      id: '/a2a-lab'
      path: '/a2a-lab'
      fullPath: '/a2a-lab'
      preLoaderRoute: typeof A2aLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaultline/$': {
      id: '/vaultline/$'
      path: '/$'
      fullPath: '/vaultline/$'
      preLoaderRoute: typeof VaultlineSplatRouteImport
      parentRoute: typeof VaultlineRoute
    }
    '/tools/$id': {
      id: '/tools/$id'
      path: '/tools/$id'
      fullPath: '/tools/$id'
      preLoaderRoute: typeof ToolsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queryline/$': {
      id: '/queryline/$'
      path: '/$'
      fullPath: '/queryline/$'
      preLoaderRoute: typeof QuerylineSplatRouteImport
      parentRoute: typeof QuerylineRoute
    }
    '/api/registry': {
      id: '/api/registry'
      path: '/api/registry'
      fullPath: '/api/registry'
      preLoaderRoute: typeof ApiRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/story-api/': {
      id: '/api/story-api/'
      path: '/api/story-api'
      fullPath: '/api/story-api/'
      preLoaderRoute: typeof ApiStoryApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/story-api/status': {
      id: '/api/story-api/status'
      path: '/api/story-api/status'
      fullPath: '/api/story-api/status'
      preLoaderRoute: typeof ApiStoryApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/story-api/$': {
      id: '/api/story-api/$'
      path: '/api/story-api/$'
      fullPath: '/api/story-api/$'
      preLoaderRoute: typeof ApiStoryApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storacha/status': {
      id: '/api/storacha/status'
      path: '/api/storacha/status'
      fullPath: '/api/storacha/status'
      preLoaderRoute: typeof ApiStorachaStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storacha/delegation': {
      id: '/api/storacha/delegation'
      path: '/api/storacha/delegation'
      fullPath: '/api/storacha/delegation'
      preLoaderRoute: typeof ApiStorachaDelegationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registry/status': {
      id: '/api/registry/status'
      path: '/status'
      fullPath: '/api/registry/status'
      preLoaderRoute: typeof ApiRegistryStatusRouteImport
      parentRoute: typeof ApiRegistryRoute
    }
    '/api/ipfs/status': {
      id: '/api/ipfs/status'
      path: '/api/ipfs/status'
      fullPath: '/api/ipfs/status'
      preLoaderRoute: typeof ApiIpfsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ipfs/pin': {
      id: '/api/ipfs/pin'
      path: '/api/ipfs/pin'
      fullPath: '/api/ipfs/pin'
      preLoaderRoute: typeof ApiIpfsPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/automata/quote': {
      id: '/api/automata/quote'
      path: '/api/automata/quote'
      fullPath: '/api/automata/quote'
      preLoaderRoute: typeof ApiAutomataQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ipfs/get/$cid': {
      id: '/api/ipfs/get/$cid'
      path: '/api/ipfs/get/$cid'
      fullPath: '/api/ipfs/get/$cid'
      preLoaderRoute: typeof ApiIpfsGetCidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface QuerylineRouteChildren {
  QuerylineSplatRoute: typeof QuerylineSplatRoute
}

const QuerylineRouteChildren: QuerylineRouteChildren = {
  QuerylineSplatRoute: QuerylineSplatRoute,
}

const QuerylineRouteWithChildren = QuerylineRoute._addFileChildren(
  QuerylineRouteChildren,
)

interface VaultlineRouteChildren {
  VaultlineSplatRoute: typeof VaultlineSplatRoute
}

const VaultlineRouteChildren: VaultlineRouteChildren = {
  VaultlineSplatRoute: VaultlineSplatRoute,
}

const VaultlineRouteWithChildren = VaultlineRoute._addFileChildren(
  VaultlineRouteChildren,
)

interface ApiRegistryRouteChildren {
  ApiRegistryStatusRoute: typeof ApiRegistryStatusRoute
}

const ApiRegistryRouteChildren: ApiRegistryRouteChildren = {
  ApiRegistryStatusRoute: ApiRegistryStatusRoute,
}

const ApiRegistryRouteWithChildren = ApiRegistryRoute._addFileChildren(
  ApiRegistryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  A2aLabRoute: A2aLabRoute,
  AgentClearanceRoute: AgentClearanceRoute,
  AgentDemoRoute: AgentDemoRoute,
  AuditRoute: AuditRoute,
  CliRoute: CliRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PaymentLabRoute: PaymentLabRoute,
  PermissionsRoute: PermissionsRoute,
  QuerylineRoute: QuerylineRouteWithChildren,
  RelayerRoute: RelayerRoute,
  SdkRoute: SdkRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  ToolOnboardingRoute: ToolOnboardingRoute,
  VaultlineRoute: VaultlineRouteWithChildren,
  VeniceEvalRoute: VeniceEvalRoute,
  ApiRegistryRoute: ApiRegistryRouteWithChildren,
  ToolsIdRoute: ToolsIdRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  ApiAutomataQuoteRoute: ApiAutomataQuoteRoute,
  ApiIpfsPinRoute: ApiIpfsPinRoute,
  ApiIpfsStatusRoute: ApiIpfsStatusRoute,
  ApiStorachaDelegationRoute: ApiStorachaDelegationRoute,
  ApiStorachaStatusRoute: ApiStorachaStatusRoute,
  ApiStoryApiSplatRoute: ApiStoryApiSplatRoute,
  ApiStoryApiStatusRoute: ApiStoryApiStatusRoute,
  ApiStoryApiIndexRoute: ApiStoryApiIndexRoute,
  ApiIpfsGetCidRoute: ApiIpfsGetCidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
