/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultlineRouteImport } from './routes/vaultline'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SdkRouteImport } from './routes/sdk'
import { Route as QuerylineRouteImport } from './routes/queryline'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CliRouteImport } from './routes/cli'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AgentRunbookRouteImport } from './routes/agent-runbook'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultlineIndexRouteImport } from './routes/vaultline.index'
import { Route as QuerylineIndexRouteImport } from './routes/queryline.index'
import { Route as VaultlineUploadRouteImport } from './routes/vaultline.upload'
import { Route as VaultlineUnlockRouteImport } from './routes/vaultline.unlock'
import { Route as VaultlineListingsRouteImport } from './routes/vaultline.listings'
import { Route as VaultlineIpRegisterRouteImport } from './routes/vaultline.ip-register'
import { Route as VaultlineDeveloperConsoleRouteImport } from './routes/vaultline.developer-console'
import { Route as VaultlineDashboardRouteImport } from './routes/vaultline.dashboard'
import { Route as VaultlineCreateVaultRouteImport } from './routes/vaultline.create-vault'
import { Route as VaultlineAuditRouteImport } from './routes/vaultline.audit'
import { Route as QuerylineResultsRouteImport } from './routes/queryline.results'
import { Route as QuerylineRequestQueryRouteImport } from './routes/queryline.request-query'
import { Route as QuerylineQueryTemplatesRouteImport } from './routes/queryline.query-templates'
import { Route as QuerylineDeveloperConsoleRouteImport } from './routes/queryline.developer-console'
import { Route as QuerylineDatasetsRouteImport } from './routes/queryline.datasets'
import { Route as QuerylineDashboardRouteImport } from './routes/queryline.dashboard'
import { Route as QuerylineCreateDatasetRouteImport } from './routes/queryline.create-dataset'
import { Route as QuerylineAuditRouteImport } from './routes/queryline.audit'
import { Route as ApiRegistryRouteImport } from './routes/api.registry'
import { Route as VaultlineVaultsIndexRouteImport } from './routes/vaultline.vaults.index'
import { Route as VaultlineListingsIndexRouteImport } from './routes/vaultline.listings.index'
import { Route as QuerylineResultsIndexRouteImport } from './routes/queryline.results.index'
import { Route as QuerylineDatasetsIndexRouteImport } from './routes/queryline.datasets.index'
import { Route as ApiStoryApiIndexRouteImport } from './routes/api.story-api.index'
import { Route as VaultlineVaultsUuidRouteImport } from './routes/vaultline.vaults.$uuid'
import { Route as VaultlineListingsIdRouteImport } from './routes/vaultline.listings.$id'
import { Route as QuerylineResultsIdRouteImport } from './routes/queryline.results.$id'
import { Route as QuerylineDatasetsIdRouteImport } from './routes/queryline.datasets.$id'
import { Route as ApiStoryApiStatusRouteImport } from './routes/api.story-api.status'
import { Route as ApiStoryApiSplatRouteImport } from './routes/api.story-api.$'
import { Route as ApiStorachaStatusRouteImport } from './routes/api.storacha.status'
import { Route as ApiStorachaDelegationRouteImport } from './routes/api.storacha.delegation'
import { Route as ApiRegistryStatusRouteImport } from './routes/api.registry.status'
import { Route as ApiIpfsStatusRouteImport } from './routes/api.ipfs.status'
import { Route as ApiIpfsPinRouteImport } from './routes/api.ipfs.pin'
import { Route as ApiAutomataQuoteRouteImport } from './routes/api.automata.quote'
import { Route as VaultlineListingsIdIndexRouteImport } from './routes/vaultline.listings.$id.index'
import { Route as VaultlineListingsIdBuyRouteImport } from './routes/vaultline.listings.$id.buy'
import { Route as ApiIpfsGetCidRouteImport } from './routes/api.ipfs.get.$cid'

const VaultlineRoute = VaultlineRouteImport.update({
  id: '/vaultline',
  path: '/vaultline',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SdkRoute = SdkRouteImport.update({
  id: '/sdk',
  path: '/sdk',
  getParentRoute: () => rootRouteImport,
} as any)
const QuerylineRoute = QuerylineRouteImport.update({
  id: '/queryline',
  path: '/queryline',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRunbookRoute = AgentRunbookRouteImport.update({
  id: '/agent-runbook',
  path: '/agent-runbook',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultlineIndexRoute = VaultlineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VaultlineRoute,
} as any)
const QuerylineIndexRoute = QuerylineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuerylineRoute,
} as any)
const VaultlineUploadRoute = VaultlineUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => VaultlineRoute,
} as any)
const VaultlineUnlockRoute = VaultlineUnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => VaultlineRoute,
} as any)
const VaultlineListingsRoute = VaultlineListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => VaultlineRoute,
} as any)
const VaultlineIpRegisterRoute = VaultlineIpRegisterRouteImport.update({
  id: '/ip-register',
  path: '/ip-register',
  getParentRoute: () => VaultlineRoute,
} as any)
const VaultlineDeveloperConsoleRoute =
  VaultlineDeveloperConsoleRouteImport.update({
    id: '/developer-console',
    path: '/developer-console',
    getParentRoute: () => VaultlineRoute,
  } as any)
const VaultlineDashboardRoute = VaultlineDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => VaultlineRoute,
} as any)
const VaultlineCreateVaultRoute = VaultlineCreateVaultRouteImport.update({
  id: '/create-vault',
  path: '/create-vault',
  getParentRoute: () => VaultlineRoute,
} as any)
const VaultlineAuditRoute = VaultlineAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => VaultlineRoute,
} as any)
const QuerylineResultsRoute = QuerylineResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => QuerylineRoute,
} as any)
const QuerylineRequestQueryRoute = QuerylineRequestQueryRouteImport.update({
  id: '/request-query',
  path: '/request-query',
  getParentRoute: () => QuerylineRoute,
} as any)
const QuerylineQueryTemplatesRoute = QuerylineQueryTemplatesRouteImport.update({
  id: '/query-templates',
  path: '/query-templates',
  getParentRoute: () => QuerylineRoute,
} as any)
const QuerylineDeveloperConsoleRoute =
  QuerylineDeveloperConsoleRouteImport.update({
    id: '/developer-console',
    path: '/developer-console',
    getParentRoute: () => QuerylineRoute,
  } as any)
const QuerylineDatasetsRoute = QuerylineDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => QuerylineRoute,
} as any)
const QuerylineDashboardRoute = QuerylineDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => QuerylineRoute,
} as any)
const QuerylineCreateDatasetRoute = QuerylineCreateDatasetRouteImport.update({
  id: '/create-dataset',
  path: '/create-dataset',
  getParentRoute: () => QuerylineRoute,
} as any)
const QuerylineAuditRoute = QuerylineAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => QuerylineRoute,
} as any)
const ApiRegistryRoute = ApiRegistryRouteImport.update({
  id: '/api/registry',
  path: '/api/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultlineVaultsIndexRoute = VaultlineVaultsIndexRouteImport.update({
  id: '/vaults/',
  path: '/vaults/',
  getParentRoute: () => VaultlineRoute,
} as any)
const VaultlineListingsIndexRoute = VaultlineListingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VaultlineListingsRoute,
} as any)
const QuerylineResultsIndexRoute = QuerylineResultsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuerylineResultsRoute,
} as any)
const QuerylineDatasetsIndexRoute = QuerylineDatasetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuerylineDatasetsRoute,
} as any)
const ApiStoryApiIndexRoute = ApiStoryApiIndexRouteImport.update({
  id: '/api/story-api/',
  path: '/api/story-api/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultlineVaultsUuidRoute = VaultlineVaultsUuidRouteImport.update({
  id: '/vaults/$uuid',
  path: '/vaults/$uuid',
  getParentRoute: () => VaultlineRoute,
} as any)
const VaultlineListingsIdRoute = VaultlineListingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VaultlineListingsRoute,
} as any)
const QuerylineResultsIdRoute = QuerylineResultsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => QuerylineResultsRoute,
} as any)
const QuerylineDatasetsIdRoute = QuerylineDatasetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => QuerylineDatasetsRoute,
} as any)
const ApiStoryApiStatusRoute = ApiStoryApiStatusRouteImport.update({
  id: '/api/story-api/status',
  path: '/api/story-api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoryApiSplatRoute = ApiStoryApiSplatRouteImport.update({
  id: '/api/story-api/$',
  path: '/api/story-api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorachaStatusRoute = ApiStorachaStatusRouteImport.update({
  id: '/api/storacha/status',
  path: '/api/storacha/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorachaDelegationRoute = ApiStorachaDelegationRouteImport.update({
  id: '/api/storacha/delegation',
  path: '/api/storacha/delegation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistryStatusRoute = ApiRegistryStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiRegistryRoute,
} as any)
const ApiIpfsStatusRoute = ApiIpfsStatusRouteImport.update({
  id: '/api/ipfs/status',
  path: '/api/ipfs/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIpfsPinRoute = ApiIpfsPinRouteImport.update({
  id: '/api/ipfs/pin',
  path: '/api/ipfs/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutomataQuoteRoute = ApiAutomataQuoteRouteImport.update({
  id: '/api/automata/quote',
  path: '/api/automata/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultlineListingsIdIndexRoute =
  VaultlineListingsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => VaultlineListingsIdRoute,
  } as any)
const VaultlineListingsIdBuyRoute = VaultlineListingsIdBuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => VaultlineListingsIdRoute,
} as any)
const ApiIpfsGetCidRoute = ApiIpfsGetCidRouteImport.update({
  id: '/api/ipfs/get/$cid',
  path: '/api/ipfs/get/$cid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-runbook': typeof AgentRunbookRoute
  '/architecture': typeof ArchitectureRoute
  '/changelog': typeof ChangelogRoute
  '/cli': typeof CliRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/queryline': typeof QuerylineRouteWithChildren
  '/sdk': typeof SdkRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/vaultline': typeof VaultlineRouteWithChildren
  '/api/registry': typeof ApiRegistryRouteWithChildren
  '/queryline/audit': typeof QuerylineAuditRoute
  '/queryline/create-dataset': typeof QuerylineCreateDatasetRoute
  '/queryline/dashboard': typeof QuerylineDashboardRoute
  '/queryline/datasets': typeof QuerylineDatasetsRouteWithChildren
  '/queryline/developer-console': typeof QuerylineDeveloperConsoleRoute
  '/queryline/query-templates': typeof QuerylineQueryTemplatesRoute
  '/queryline/request-query': typeof QuerylineRequestQueryRoute
  '/queryline/results': typeof QuerylineResultsRouteWithChildren
  '/vaultline/audit': typeof VaultlineAuditRoute
  '/vaultline/create-vault': typeof VaultlineCreateVaultRoute
  '/vaultline/dashboard': typeof VaultlineDashboardRoute
  '/vaultline/developer-console': typeof VaultlineDeveloperConsoleRoute
  '/vaultline/ip-register': typeof VaultlineIpRegisterRoute
  '/vaultline/listings': typeof VaultlineListingsRouteWithChildren
  '/vaultline/unlock': typeof VaultlineUnlockRoute
  '/vaultline/upload': typeof VaultlineUploadRoute
  '/queryline/': typeof QuerylineIndexRoute
  '/vaultline/': typeof VaultlineIndexRoute
  '/api/automata/quote': typeof ApiAutomataQuoteRoute
  '/api/ipfs/pin': typeof ApiIpfsPinRoute
  '/api/ipfs/status': typeof ApiIpfsStatusRoute
  '/api/registry/status': typeof ApiRegistryStatusRoute
  '/api/storacha/delegation': typeof ApiStorachaDelegationRoute
  '/api/storacha/status': typeof ApiStorachaStatusRoute
  '/api/story-api/$': typeof ApiStoryApiSplatRoute
  '/api/story-api/status': typeof ApiStoryApiStatusRoute
  '/queryline/datasets/$id': typeof QuerylineDatasetsIdRoute
  '/queryline/results/$id': typeof QuerylineResultsIdRoute
  '/vaultline/listings/$id': typeof VaultlineListingsIdRouteWithChildren
  '/vaultline/vaults/$uuid': typeof VaultlineVaultsUuidRoute
  '/api/story-api/': typeof ApiStoryApiIndexRoute
  '/queryline/datasets/': typeof QuerylineDatasetsIndexRoute
  '/queryline/results/': typeof QuerylineResultsIndexRoute
  '/vaultline/listings/': typeof VaultlineListingsIndexRoute
  '/vaultline/vaults/': typeof VaultlineVaultsIndexRoute
  '/api/ipfs/get/$cid': typeof ApiIpfsGetCidRoute
  '/vaultline/listings/$id/buy': typeof VaultlineListingsIdBuyRoute
  '/vaultline/listings/$id/': typeof VaultlineListingsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-runbook': typeof AgentRunbookRoute
  '/architecture': typeof ArchitectureRoute
  '/changelog': typeof ChangelogRoute
  '/cli': typeof CliRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/sdk': typeof SdkRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/api/registry': typeof ApiRegistryRouteWithChildren
  '/queryline/audit': typeof QuerylineAuditRoute
  '/queryline/create-dataset': typeof QuerylineCreateDatasetRoute
  '/queryline/dashboard': typeof QuerylineDashboardRoute
  '/queryline/developer-console': typeof QuerylineDeveloperConsoleRoute
  '/queryline/query-templates': typeof QuerylineQueryTemplatesRoute
  '/queryline/request-query': typeof QuerylineRequestQueryRoute
  '/vaultline/audit': typeof VaultlineAuditRoute
  '/vaultline/create-vault': typeof VaultlineCreateVaultRoute
  '/vaultline/dashboard': typeof VaultlineDashboardRoute
  '/vaultline/developer-console': typeof VaultlineDeveloperConsoleRoute
  '/vaultline/ip-register': typeof VaultlineIpRegisterRoute
  '/vaultline/unlock': typeof VaultlineUnlockRoute
  '/vaultline/upload': typeof VaultlineUploadRoute
  '/queryline': typeof QuerylineIndexRoute
  '/vaultline': typeof VaultlineIndexRoute
  '/api/automata/quote': typeof ApiAutomataQuoteRoute
  '/api/ipfs/pin': typeof ApiIpfsPinRoute
  '/api/ipfs/status': typeof ApiIpfsStatusRoute
  '/api/registry/status': typeof ApiRegistryStatusRoute
  '/api/storacha/delegation': typeof ApiStorachaDelegationRoute
  '/api/storacha/status': typeof ApiStorachaStatusRoute
  '/api/story-api/$': typeof ApiStoryApiSplatRoute
  '/api/story-api/status': typeof ApiStoryApiStatusRoute
  '/queryline/datasets/$id': typeof QuerylineDatasetsIdRoute
  '/queryline/results/$id': typeof QuerylineResultsIdRoute
  '/vaultline/vaults/$uuid': typeof VaultlineVaultsUuidRoute
  '/api/story-api': typeof ApiStoryApiIndexRoute
  '/queryline/datasets': typeof QuerylineDatasetsIndexRoute
  '/queryline/results': typeof QuerylineResultsIndexRoute
  '/vaultline/listings': typeof VaultlineListingsIndexRoute
  '/vaultline/vaults': typeof VaultlineVaultsIndexRoute
  '/api/ipfs/get/$cid': typeof ApiIpfsGetCidRoute
  '/vaultline/listings/$id/buy': typeof VaultlineListingsIdBuyRoute
  '/vaultline/listings/$id': typeof VaultlineListingsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-runbook': typeof AgentRunbookRoute
  '/architecture': typeof ArchitectureRoute
  '/changelog': typeof ChangelogRoute
  '/cli': typeof CliRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/queryline': typeof QuerylineRouteWithChildren
  '/sdk': typeof SdkRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/vaultline': typeof VaultlineRouteWithChildren
  '/api/registry': typeof ApiRegistryRouteWithChildren
  '/queryline/audit': typeof QuerylineAuditRoute
  '/queryline/create-dataset': typeof QuerylineCreateDatasetRoute
  '/queryline/dashboard': typeof QuerylineDashboardRoute
  '/queryline/datasets': typeof QuerylineDatasetsRouteWithChildren
  '/queryline/developer-console': typeof QuerylineDeveloperConsoleRoute
  '/queryline/query-templates': typeof QuerylineQueryTemplatesRoute
  '/queryline/request-query': typeof QuerylineRequestQueryRoute
  '/queryline/results': typeof QuerylineResultsRouteWithChildren
  '/vaultline/audit': typeof VaultlineAuditRoute
  '/vaultline/create-vault': typeof VaultlineCreateVaultRoute
  '/vaultline/dashboard': typeof VaultlineDashboardRoute
  '/vaultline/developer-console': typeof VaultlineDeveloperConsoleRoute
  '/vaultline/ip-register': typeof VaultlineIpRegisterRoute
  '/vaultline/listings': typeof VaultlineListingsRouteWithChildren
  '/vaultline/unlock': typeof VaultlineUnlockRoute
  '/vaultline/upload': typeof VaultlineUploadRoute
  '/queryline/': typeof QuerylineIndexRoute
  '/vaultline/': typeof VaultlineIndexRoute
  '/api/automata/quote': typeof ApiAutomataQuoteRoute
  '/api/ipfs/pin': typeof ApiIpfsPinRoute
  '/api/ipfs/status': typeof ApiIpfsStatusRoute
  '/api/registry/status': typeof ApiRegistryStatusRoute
  '/api/storacha/delegation': typeof ApiStorachaDelegationRoute
  '/api/storacha/status': typeof ApiStorachaStatusRoute
  '/api/story-api/$': typeof ApiStoryApiSplatRoute
  '/api/story-api/status': typeof ApiStoryApiStatusRoute
  '/queryline/datasets/$id': typeof QuerylineDatasetsIdRoute
  '/queryline/results/$id': typeof QuerylineResultsIdRoute
  '/vaultline/listings/$id': typeof VaultlineListingsIdRouteWithChildren
  '/vaultline/vaults/$uuid': typeof VaultlineVaultsUuidRoute
  '/api/story-api/': typeof ApiStoryApiIndexRoute
  '/queryline/datasets/': typeof QuerylineDatasetsIndexRoute
  '/queryline/results/': typeof QuerylineResultsIndexRoute
  '/vaultline/listings/': typeof VaultlineListingsIndexRoute
  '/vaultline/vaults/': typeof VaultlineVaultsIndexRoute
  '/api/ipfs/get/$cid': typeof ApiIpfsGetCidRoute
  '/vaultline/listings/$id/buy': typeof VaultlineListingsIdBuyRoute
  '/vaultline/listings/$id/': typeof VaultlineListingsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-runbook'
    | '/architecture'
    | '/changelog'
    | '/cli'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/mcp'
    | '/queryline'
    | '/sdk'
    | '/settings'
    | '/status'
    | '/vaultline'
    | '/api/registry'
    | '/queryline/audit'
    | '/queryline/create-dataset'
    | '/queryline/dashboard'
    | '/queryline/datasets'
    | '/queryline/developer-console'
    | '/queryline/query-templates'
    | '/queryline/request-query'
    | '/queryline/results'
    | '/vaultline/audit'
    | '/vaultline/create-vault'
    | '/vaultline/dashboard'
    | '/vaultline/developer-console'
    | '/vaultline/ip-register'
    | '/vaultline/listings'
    | '/vaultline/unlock'
    | '/vaultline/upload'
    | '/queryline/'
    | '/vaultline/'
    | '/api/automata/quote'
    | '/api/ipfs/pin'
    | '/api/ipfs/status'
    | '/api/registry/status'
    | '/api/storacha/delegation'
    | '/api/storacha/status'
    | '/api/story-api/$'
    | '/api/story-api/status'
    | '/queryline/datasets/$id'
    | '/queryline/results/$id'
    | '/vaultline/listings/$id'
    | '/vaultline/vaults/$uuid'
    | '/api/story-api/'
    | '/queryline/datasets/'
    | '/queryline/results/'
    | '/vaultline/listings/'
    | '/vaultline/vaults/'
    | '/api/ipfs/get/$cid'
    | '/vaultline/listings/$id/buy'
    | '/vaultline/listings/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-runbook'
    | '/architecture'
    | '/changelog'
    | '/cli'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/mcp'
    | '/sdk'
    | '/settings'
    | '/status'
    | '/api/registry'
    | '/queryline/audit'
    | '/queryline/create-dataset'
    | '/queryline/dashboard'
    | '/queryline/developer-console'
    | '/queryline/query-templates'
    | '/queryline/request-query'
    | '/vaultline/audit'
    | '/vaultline/create-vault'
    | '/vaultline/dashboard'
    | '/vaultline/developer-console'
    | '/vaultline/ip-register'
    | '/vaultline/unlock'
    | '/vaultline/upload'
    | '/queryline'
    | '/vaultline'
    | '/api/automata/quote'
    | '/api/ipfs/pin'
    | '/api/ipfs/status'
    | '/api/registry/status'
    | '/api/storacha/delegation'
    | '/api/storacha/status'
    | '/api/story-api/$'
    | '/api/story-api/status'
    | '/queryline/datasets/$id'
    | '/queryline/results/$id'
    | '/vaultline/vaults/$uuid'
    | '/api/story-api'
    | '/queryline/datasets'
    | '/queryline/results'
    | '/vaultline/listings'
    | '/vaultline/vaults'
    | '/api/ipfs/get/$cid'
    | '/vaultline/listings/$id/buy'
    | '/vaultline/listings/$id'
  id:
    | '__root__'
    | '/'
    | '/agent-runbook'
    | '/architecture'
    | '/changelog'
    | '/cli'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/mcp'
    | '/queryline'
    | '/sdk'
    | '/settings'
    | '/status'
    | '/vaultline'
    | '/api/registry'
    | '/queryline/audit'
    | '/queryline/create-dataset'
    | '/queryline/dashboard'
    | '/queryline/datasets'
    | '/queryline/developer-console'
    | '/queryline/query-templates'
    | '/queryline/request-query'
    | '/queryline/results'
    | '/vaultline/audit'
    | '/vaultline/create-vault'
    | '/vaultline/dashboard'
    | '/vaultline/developer-console'
    | '/vaultline/ip-register'
    | '/vaultline/listings'
    | '/vaultline/unlock'
    | '/vaultline/upload'
    | '/queryline/'
    | '/vaultline/'
    | '/api/automata/quote'
    | '/api/ipfs/pin'
    | '/api/ipfs/status'
    | '/api/registry/status'
    | '/api/storacha/delegation'
    | '/api/storacha/status'
    | '/api/story-api/$'
    | '/api/story-api/status'
    | '/queryline/datasets/$id'
    | '/queryline/results/$id'
    | '/vaultline/listings/$id'
    | '/vaultline/vaults/$uuid'
    | '/api/story-api/'
    | '/queryline/datasets/'
    | '/queryline/results/'
    | '/vaultline/listings/'
    | '/vaultline/vaults/'
    | '/api/ipfs/get/$cid'
    | '/vaultline/listings/$id/buy'
    | '/vaultline/listings/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRunbookRoute: typeof AgentRunbookRoute
  ArchitectureRoute: typeof ArchitectureRoute
  ChangelogRoute: typeof ChangelogRoute
  CliRoute: typeof CliRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  QuerylineRoute: typeof QuerylineRouteWithChildren
  SdkRoute: typeof SdkRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  VaultlineRoute: typeof VaultlineRouteWithChildren
  ApiRegistryRoute: typeof ApiRegistryRouteWithChildren
  ApiAutomataQuoteRoute: typeof ApiAutomataQuoteRoute
  ApiIpfsPinRoute: typeof ApiIpfsPinRoute
  ApiIpfsStatusRoute: typeof ApiIpfsStatusRoute
  ApiStorachaDelegationRoute: typeof ApiStorachaDelegationRoute
  ApiStorachaStatusRoute: typeof ApiStorachaStatusRoute
  ApiStoryApiSplatRoute: typeof ApiStoryApiSplatRoute
  ApiStoryApiStatusRoute: typeof ApiStoryApiStatusRoute
  ApiStoryApiIndexRoute: typeof ApiStoryApiIndexRoute
  ApiIpfsGetCidRoute: typeof ApiIpfsGetCidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vaultline': {
      id: '/vaultline'
      path: '/vaultline'
      fullPath: '/vaultline'
      preLoaderRoute: typeof VaultlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdk': {
      id: '/sdk'
      path: '/sdk'
      fullPath: '/sdk'
      preLoaderRoute: typeof SdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queryline': {
      id: '/queryline'
      path: '/queryline'
      fullPath: '/queryline'
      preLoaderRoute: typeof QuerylineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-runbook': {
      id: '/agent-runbook'
      path: '/agent-runbook'
      fullPath: '/agent-runbook'
      preLoaderRoute: typeof AgentRunbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaultline/': {
      id: '/vaultline/'
      path: '/'
      fullPath: '/vaultline/'
      preLoaderRoute: typeof VaultlineIndexRouteImport
      parentRoute: typeof VaultlineRoute
    }
    '/queryline/': {
      id: '/queryline/'
      path: '/'
      fullPath: '/queryline/'
      preLoaderRoute: typeof QuerylineIndexRouteImport
      parentRoute: typeof QuerylineRoute
    }
    '/vaultline/upload': {
      id: '/vaultline/upload'
      path: '/upload'
      fullPath: '/vaultline/upload'
      preLoaderRoute: typeof VaultlineUploadRouteImport
      parentRoute: typeof VaultlineRoute
    }
    '/vaultline/unlock': {
      id: '/vaultline/unlock'
      path: '/unlock'
      fullPath: '/vaultline/unlock'
      preLoaderRoute: typeof VaultlineUnlockRouteImport
      parentRoute: typeof VaultlineRoute
    }
    '/vaultline/listings': {
      id: '/vaultline/listings'
      path: '/listings'
      fullPath: '/vaultline/listings'
      preLoaderRoute: typeof VaultlineListingsRouteImport
      parentRoute: typeof VaultlineRoute
    }
    '/vaultline/ip-register': {
      id: '/vaultline/ip-register'
      path: '/ip-register'
      fullPath: '/vaultline/ip-register'
      preLoaderRoute: typeof VaultlineIpRegisterRouteImport
      parentRoute: typeof VaultlineRoute
    }
    '/vaultline/developer-console': {
      id: '/vaultline/developer-console'
      path: '/developer-console'
      fullPath: '/vaultline/developer-console'
      preLoaderRoute: typeof VaultlineDeveloperConsoleRouteImport
      parentRoute: typeof VaultlineRoute
    }
    '/vaultline/dashboard': {
      id: '/vaultline/dashboard'
      path: '/dashboard'
      fullPath: '/vaultline/dashboard'
      preLoaderRoute: typeof VaultlineDashboardRouteImport
      parentRoute: typeof VaultlineRoute
    }
    '/vaultline/create-vault': {
      id: '/vaultline/create-vault'
      path: '/create-vault'
      fullPath: '/vaultline/create-vault'
      preLoaderRoute: typeof VaultlineCreateVaultRouteImport
      parentRoute: typeof VaultlineRoute
    }
    '/vaultline/audit': {
      id: '/vaultline/audit'
      path: '/audit'
      fullPath: '/vaultline/audit'
      preLoaderRoute: typeof VaultlineAuditRouteImport
      parentRoute: typeof VaultlineRoute
    }
    '/queryline/results': {
      id: '/queryline/results'
      path: '/results'
      fullPath: '/queryline/results'
      preLoaderRoute: typeof QuerylineResultsRouteImport
      parentRoute: typeof QuerylineRoute
    }
    '/queryline/request-query': {
      id: '/queryline/request-query'
      path: '/request-query'
      fullPath: '/queryline/request-query'
      preLoaderRoute: typeof QuerylineRequestQueryRouteImport
      parentRoute: typeof QuerylineRoute
    }
    '/queryline/query-templates': {
      id: '/queryline/query-templates'
      path: '/query-templates'
      fullPath: '/queryline/query-templates'
      preLoaderRoute: typeof QuerylineQueryTemplatesRouteImport
      parentRoute: typeof QuerylineRoute
    }
    '/queryline/developer-console': {
      id: '/queryline/developer-console'
      path: '/developer-console'
      fullPath: '/queryline/developer-console'
      preLoaderRoute: typeof QuerylineDeveloperConsoleRouteImport
      parentRoute: typeof QuerylineRoute
    }
    '/queryline/datasets': {
      id: '/queryline/datasets'
      path: '/datasets'
      fullPath: '/queryline/datasets'
      preLoaderRoute: typeof QuerylineDatasetsRouteImport
      parentRoute: typeof QuerylineRoute
    }
    '/queryline/dashboard': {
      id: '/queryline/dashboard'
      path: '/dashboard'
      fullPath: '/queryline/dashboard'
      preLoaderRoute: typeof QuerylineDashboardRouteImport
      parentRoute: typeof QuerylineRoute
    }
    '/queryline/create-dataset': {
      id: '/queryline/create-dataset'
      path: '/create-dataset'
      fullPath: '/queryline/create-dataset'
      preLoaderRoute: typeof QuerylineCreateDatasetRouteImport
      parentRoute: typeof QuerylineRoute
    }
    '/queryline/audit': {
      id: '/queryline/audit'
      path: '/audit'
      fullPath: '/queryline/audit'
      preLoaderRoute: typeof QuerylineAuditRouteImport
      parentRoute: typeof QuerylineRoute
    }
    '/api/registry': {
      id: '/api/registry'
      path: '/api/registry'
      fullPath: '/api/registry'
      preLoaderRoute: typeof ApiRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaultline/vaults/': {
      id: '/vaultline/vaults/'
      path: '/vaults'
      fullPath: '/vaultline/vaults/'
      preLoaderRoute: typeof VaultlineVaultsIndexRouteImport
      parentRoute: typeof VaultlineRoute
    }
    '/vaultline/listings/': {
      id: '/vaultline/listings/'
      path: '/'
      fullPath: '/vaultline/listings/'
      preLoaderRoute: typeof VaultlineListingsIndexRouteImport
      parentRoute: typeof VaultlineListingsRoute
    }
    '/queryline/results/': {
      id: '/queryline/results/'
      path: '/'
      fullPath: '/queryline/results/'
      preLoaderRoute: typeof QuerylineResultsIndexRouteImport
      parentRoute: typeof QuerylineResultsRoute
    }
    '/queryline/datasets/': {
      id: '/queryline/datasets/'
      path: '/'
      fullPath: '/queryline/datasets/'
      preLoaderRoute: typeof QuerylineDatasetsIndexRouteImport
      parentRoute: typeof QuerylineDatasetsRoute
    }
    '/api/story-api/': {
      id: '/api/story-api/'
      path: '/api/story-api'
      fullPath: '/api/story-api/'
      preLoaderRoute: typeof ApiStoryApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaultline/vaults/$uuid': {
      id: '/vaultline/vaults/$uuid'
      path: '/vaults/$uuid'
      fullPath: '/vaultline/vaults/$uuid'
      preLoaderRoute: typeof VaultlineVaultsUuidRouteImport
      parentRoute: typeof VaultlineRoute
    }
    '/vaultline/listings/$id': {
      id: '/vaultline/listings/$id'
      path: '/$id'
      fullPath: '/vaultline/listings/$id'
      preLoaderRoute: typeof VaultlineListingsIdRouteImport
      parentRoute: typeof VaultlineListingsRoute
    }
    '/queryline/results/$id': {
      id: '/queryline/results/$id'
      path: '/$id'
      fullPath: '/queryline/results/$id'
      preLoaderRoute: typeof QuerylineResultsIdRouteImport
      parentRoute: typeof QuerylineResultsRoute
    }
    '/queryline/datasets/$id': {
      id: '/queryline/datasets/$id'
      path: '/$id'
      fullPath: '/queryline/datasets/$id'
      preLoaderRoute: typeof QuerylineDatasetsIdRouteImport
      parentRoute: typeof QuerylineDatasetsRoute
    }
    '/api/story-api/status': {
      id: '/api/story-api/status'
      path: '/api/story-api/status'
      fullPath: '/api/story-api/status'
      preLoaderRoute: typeof ApiStoryApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/story-api/$': {
      id: '/api/story-api/$'
      path: '/api/story-api/$'
      fullPath: '/api/story-api/$'
      preLoaderRoute: typeof ApiStoryApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storacha/status': {
      id: '/api/storacha/status'
      path: '/api/storacha/status'
      fullPath: '/api/storacha/status'
      preLoaderRoute: typeof ApiStorachaStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storacha/delegation': {
      id: '/api/storacha/delegation'
      path: '/api/storacha/delegation'
      fullPath: '/api/storacha/delegation'
      preLoaderRoute: typeof ApiStorachaDelegationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registry/status': {
      id: '/api/registry/status'
      path: '/status'
      fullPath: '/api/registry/status'
      preLoaderRoute: typeof ApiRegistryStatusRouteImport
      parentRoute: typeof ApiRegistryRoute
    }
    '/api/ipfs/status': {
      id: '/api/ipfs/status'
      path: '/api/ipfs/status'
      fullPath: '/api/ipfs/status'
      preLoaderRoute: typeof ApiIpfsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ipfs/pin': {
      id: '/api/ipfs/pin'
      path: '/api/ipfs/pin'
      fullPath: '/api/ipfs/pin'
      preLoaderRoute: typeof ApiIpfsPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/automata/quote': {
      id: '/api/automata/quote'
      path: '/api/automata/quote'
      fullPath: '/api/automata/quote'
      preLoaderRoute: typeof ApiAutomataQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaultline/listings/$id/': {
      id: '/vaultline/listings/$id/'
      path: '/'
      fullPath: '/vaultline/listings/$id/'
      preLoaderRoute: typeof VaultlineListingsIdIndexRouteImport
      parentRoute: typeof VaultlineListingsIdRoute
    }
    '/vaultline/listings/$id/buy': {
      id: '/vaultline/listings/$id/buy'
      path: '/buy'
      fullPath: '/vaultline/listings/$id/buy'
      preLoaderRoute: typeof VaultlineListingsIdBuyRouteImport
      parentRoute: typeof VaultlineListingsIdRoute
    }
    '/api/ipfs/get/$cid': {
      id: '/api/ipfs/get/$cid'
      path: '/api/ipfs/get/$cid'
      fullPath: '/api/ipfs/get/$cid'
      preLoaderRoute: typeof ApiIpfsGetCidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface QuerylineDatasetsRouteChildren {
  QuerylineDatasetsIdRoute: typeof QuerylineDatasetsIdRoute
  QuerylineDatasetsIndexRoute: typeof QuerylineDatasetsIndexRoute
}

const QuerylineDatasetsRouteChildren: QuerylineDatasetsRouteChildren = {
  QuerylineDatasetsIdRoute: QuerylineDatasetsIdRoute,
  QuerylineDatasetsIndexRoute: QuerylineDatasetsIndexRoute,
}

const QuerylineDatasetsRouteWithChildren =
  QuerylineDatasetsRoute._addFileChildren(QuerylineDatasetsRouteChildren)

interface QuerylineResultsRouteChildren {
  QuerylineResultsIdRoute: typeof QuerylineResultsIdRoute
  QuerylineResultsIndexRoute: typeof QuerylineResultsIndexRoute
}

const QuerylineResultsRouteChildren: QuerylineResultsRouteChildren = {
  QuerylineResultsIdRoute: QuerylineResultsIdRoute,
  QuerylineResultsIndexRoute: QuerylineResultsIndexRoute,
}

const QuerylineResultsRouteWithChildren =
  QuerylineResultsRoute._addFileChildren(QuerylineResultsRouteChildren)

interface QuerylineRouteChildren {
  QuerylineAuditRoute: typeof QuerylineAuditRoute
  QuerylineCreateDatasetRoute: typeof QuerylineCreateDatasetRoute
  QuerylineDashboardRoute: typeof QuerylineDashboardRoute
  QuerylineDatasetsRoute: typeof QuerylineDatasetsRouteWithChildren
  QuerylineDeveloperConsoleRoute: typeof QuerylineDeveloperConsoleRoute
  QuerylineQueryTemplatesRoute: typeof QuerylineQueryTemplatesRoute
  QuerylineRequestQueryRoute: typeof QuerylineRequestQueryRoute
  QuerylineResultsRoute: typeof QuerylineResultsRouteWithChildren
  QuerylineIndexRoute: typeof QuerylineIndexRoute
}

const QuerylineRouteChildren: QuerylineRouteChildren = {
  QuerylineAuditRoute: QuerylineAuditRoute,
  QuerylineCreateDatasetRoute: QuerylineCreateDatasetRoute,
  QuerylineDashboardRoute: QuerylineDashboardRoute,
  QuerylineDatasetsRoute: QuerylineDatasetsRouteWithChildren,
  QuerylineDeveloperConsoleRoute: QuerylineDeveloperConsoleRoute,
  QuerylineQueryTemplatesRoute: QuerylineQueryTemplatesRoute,
  QuerylineRequestQueryRoute: QuerylineRequestQueryRoute,
  QuerylineResultsRoute: QuerylineResultsRouteWithChildren,
  QuerylineIndexRoute: QuerylineIndexRoute,
}

const QuerylineRouteWithChildren = QuerylineRoute._addFileChildren(
  QuerylineRouteChildren,
)

interface VaultlineListingsIdRouteChildren {
  VaultlineListingsIdBuyRoute: typeof VaultlineListingsIdBuyRoute
  VaultlineListingsIdIndexRoute: typeof VaultlineListingsIdIndexRoute
}

const VaultlineListingsIdRouteChildren: VaultlineListingsIdRouteChildren = {
  VaultlineListingsIdBuyRoute: VaultlineListingsIdBuyRoute,
  VaultlineListingsIdIndexRoute: VaultlineListingsIdIndexRoute,
}

const VaultlineListingsIdRouteWithChildren =
  VaultlineListingsIdRoute._addFileChildren(VaultlineListingsIdRouteChildren)

interface VaultlineListingsRouteChildren {
  VaultlineListingsIdRoute: typeof VaultlineListingsIdRouteWithChildren
  VaultlineListingsIndexRoute: typeof VaultlineListingsIndexRoute
}

const VaultlineListingsRouteChildren: VaultlineListingsRouteChildren = {
  VaultlineListingsIdRoute: VaultlineListingsIdRouteWithChildren,
  VaultlineListingsIndexRoute: VaultlineListingsIndexRoute,
}

const VaultlineListingsRouteWithChildren =
  VaultlineListingsRoute._addFileChildren(VaultlineListingsRouteChildren)

interface VaultlineRouteChildren {
  VaultlineAuditRoute: typeof VaultlineAuditRoute
  VaultlineCreateVaultRoute: typeof VaultlineCreateVaultRoute
  VaultlineDashboardRoute: typeof VaultlineDashboardRoute
  VaultlineDeveloperConsoleRoute: typeof VaultlineDeveloperConsoleRoute
  VaultlineIpRegisterRoute: typeof VaultlineIpRegisterRoute
  VaultlineListingsRoute: typeof VaultlineListingsRouteWithChildren
  VaultlineUnlockRoute: typeof VaultlineUnlockRoute
  VaultlineUploadRoute: typeof VaultlineUploadRoute
  VaultlineIndexRoute: typeof VaultlineIndexRoute
  VaultlineVaultsUuidRoute: typeof VaultlineVaultsUuidRoute
  VaultlineVaultsIndexRoute: typeof VaultlineVaultsIndexRoute
}

const VaultlineRouteChildren: VaultlineRouteChildren = {
  VaultlineAuditRoute: VaultlineAuditRoute,
  VaultlineCreateVaultRoute: VaultlineCreateVaultRoute,
  VaultlineDashboardRoute: VaultlineDashboardRoute,
  VaultlineDeveloperConsoleRoute: VaultlineDeveloperConsoleRoute,
  VaultlineIpRegisterRoute: VaultlineIpRegisterRoute,
  VaultlineListingsRoute: VaultlineListingsRouteWithChildren,
  VaultlineUnlockRoute: VaultlineUnlockRoute,
  VaultlineUploadRoute: VaultlineUploadRoute,
  VaultlineIndexRoute: VaultlineIndexRoute,
  VaultlineVaultsUuidRoute: VaultlineVaultsUuidRoute,
  VaultlineVaultsIndexRoute: VaultlineVaultsIndexRoute,
}

const VaultlineRouteWithChildren = VaultlineRoute._addFileChildren(
  VaultlineRouteChildren,
)

interface ApiRegistryRouteChildren {
  ApiRegistryStatusRoute: typeof ApiRegistryStatusRoute
}

const ApiRegistryRouteChildren: ApiRegistryRouteChildren = {
  ApiRegistryStatusRoute: ApiRegistryStatusRoute,
}

const ApiRegistryRouteWithChildren = ApiRegistryRoute._addFileChildren(
  ApiRegistryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRunbookRoute: AgentRunbookRoute,
  ArchitectureRoute: ArchitectureRoute,
  ChangelogRoute: ChangelogRoute,
  CliRoute: CliRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  QuerylineRoute: QuerylineRouteWithChildren,
  SdkRoute: SdkRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  VaultlineRoute: VaultlineRouteWithChildren,
  ApiRegistryRoute: ApiRegistryRouteWithChildren,
  ApiAutomataQuoteRoute: ApiAutomataQuoteRoute,
  ApiIpfsPinRoute: ApiIpfsPinRoute,
  ApiIpfsStatusRoute: ApiIpfsStatusRoute,
  ApiStorachaDelegationRoute: ApiStorachaDelegationRoute,
  ApiStorachaStatusRoute: ApiStorachaStatusRoute,
  ApiStoryApiSplatRoute: ApiStoryApiSplatRoute,
  ApiStoryApiStatusRoute: ApiStoryApiStatusRoute,
  ApiStoryApiIndexRoute: ApiStoryApiIndexRoute,
  ApiIpfsGetCidRoute: ApiIpfsGetCidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
