/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VeniceEvalRouteImport } from './routes/venice-eval'
import { Route as ToolOnboardingRouteImport } from './routes/tool-onboarding'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SdkRouteImport } from './routes/sdk'
import { Route as RelayerRouteImport } from './routes/relayer'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as PaymentLabRouteImport } from './routes/payment-lab'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CliRouteImport } from './routes/cli'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AgentDemoRouteImport } from './routes/agent-demo'
import { Route as AgentClearanceRouteImport } from './routes/agent-clearance'
import { Route as A2aLabRouteImport } from './routes/a2a-lab'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsIdRouteImport } from './routes/tools.$id'
import { Route as ApiDemoX402RouteImport } from './routes/api.demo.x402'
import { Route as ApiClearanceVeniceEvalRouteImport } from './routes/api.clearance.venice-eval'
import { Route as ApiClearanceToolsRouteImport } from './routes/api.clearance.tools'
import { Route as ApiClearanceStatusRouteImport } from './routes/api.clearance.status'
import { Route as ApiClearanceSessionRouteImport } from './routes/api.clearance.session'
import { Route as ApiClearanceProbeRouteImport } from './routes/api.clearance.probe'
import { Route as ApiClearancePermissionsRouteImport } from './routes/api.clearance.permissions'
import { Route as ApiClearancePayRouteImport } from './routes/api.clearance.pay'
import { Route as ApiClearanceCheckRouteImport } from './routes/api.clearance.check'
import { Route as ApiClearanceAuditRouteImport } from './routes/api.clearance.audit'
import { Route as ApiClearanceAccountRouteImport } from './routes/api.clearance.account'
import { Route as ApiClearanceA2aRouteImport } from './routes/api.clearance.a2a'

const VeniceEvalRoute = VeniceEvalRouteImport.update({
  id: '/venice-eval',
  path: '/venice-eval',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolOnboardingRoute = ToolOnboardingRouteImport.update({
  id: '/tool-onboarding',
  path: '/tool-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SdkRoute = SdkRouteImport.update({
  id: '/sdk',
  path: '/sdk',
  getParentRoute: () => rootRouteImport,
} as any)
const RelayerRoute = RelayerRouteImport.update({
  id: '/relayer',
  path: '/relayer',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentLabRoute = PaymentLabRouteImport.update({
  id: '/payment-lab',
  path: '/payment-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDemoRoute = AgentDemoRouteImport.update({
  id: '/agent-demo',
  path: '/agent-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentClearanceRoute = AgentClearanceRouteImport.update({
  id: '/agent-clearance',
  path: '/agent-clearance',
  getParentRoute: () => rootRouteImport,
} as any)
const A2aLabRoute = A2aLabRouteImport.update({
  id: '/a2a-lab',
  path: '/a2a-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIdRoute = ToolsIdRouteImport.update({
  id: '/tools/$id',
  path: '/tools/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoX402Route = ApiDemoX402RouteImport.update({
  id: '/api/demo/x402',
  path: '/api/demo/x402',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClearanceVeniceEvalRoute = ApiClearanceVeniceEvalRouteImport.update({
  id: '/api/clearance/venice-eval',
  path: '/api/clearance/venice-eval',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClearanceToolsRoute = ApiClearanceToolsRouteImport.update({
  id: '/api/clearance/tools',
  path: '/api/clearance/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClearanceStatusRoute = ApiClearanceStatusRouteImport.update({
  id: '/api/clearance/status',
  path: '/api/clearance/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClearanceSessionRoute = ApiClearanceSessionRouteImport.update({
  id: '/api/clearance/session',
  path: '/api/clearance/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClearanceProbeRoute = ApiClearanceProbeRouteImport.update({
  id: '/api/clearance/probe',
  path: '/api/clearance/probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClearancePermissionsRoute = ApiClearancePermissionsRouteImport.update({
  id: '/api/clearance/permissions',
  path: '/api/clearance/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClearancePayRoute = ApiClearancePayRouteImport.update({
  id: '/api/clearance/pay',
  path: '/api/clearance/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClearanceCheckRoute = ApiClearanceCheckRouteImport.update({
  id: '/api/clearance/check',
  path: '/api/clearance/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClearanceAuditRoute = ApiClearanceAuditRouteImport.update({
  id: '/api/clearance/audit',
  path: '/api/clearance/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClearanceAccountRoute = ApiClearanceAccountRouteImport.update({
  id: '/api/clearance/account',
  path: '/api/clearance/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClearanceA2aRoute = ApiClearanceA2aRouteImport.update({
  id: '/api/clearance/a2a',
  path: '/api/clearance/a2a',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/a2a-lab': typeof A2aLabRoute
  '/agent-clearance': typeof AgentClearanceRoute
  '/agent-demo': typeof AgentDemoRoute
  '/audit': typeof AuditRoute
  '/cli': typeof CliRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/payment-lab': typeof PaymentLabRoute
  '/permissions': typeof PermissionsRoute
  '/relayer': typeof RelayerRoute
  '/sdk': typeof SdkRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/tool-onboarding': typeof ToolOnboardingRoute
  '/venice-eval': typeof VeniceEvalRoute
  '/tools/$id': typeof ToolsIdRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/clearance/a2a': typeof ApiClearanceA2aRoute
  '/api/clearance/account': typeof ApiClearanceAccountRoute
  '/api/clearance/audit': typeof ApiClearanceAuditRoute
  '/api/clearance/check': typeof ApiClearanceCheckRoute
  '/api/clearance/pay': typeof ApiClearancePayRoute
  '/api/clearance/permissions': typeof ApiClearancePermissionsRoute
  '/api/clearance/probe': typeof ApiClearanceProbeRoute
  '/api/clearance/session': typeof ApiClearanceSessionRoute
  '/api/clearance/status': typeof ApiClearanceStatusRoute
  '/api/clearance/tools': typeof ApiClearanceToolsRoute
  '/api/clearance/venice-eval': typeof ApiClearanceVeniceEvalRoute
  '/api/demo/x402': typeof ApiDemoX402Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/a2a-lab': typeof A2aLabRoute
  '/agent-clearance': typeof AgentClearanceRoute
  '/agent-demo': typeof AgentDemoRoute
  '/audit': typeof AuditRoute
  '/cli': typeof CliRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/payment-lab': typeof PaymentLabRoute
  '/permissions': typeof PermissionsRoute
  '/relayer': typeof RelayerRoute
  '/sdk': typeof SdkRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/tool-onboarding': typeof ToolOnboardingRoute
  '/venice-eval': typeof VeniceEvalRoute
  '/tools/$id': typeof ToolsIdRoute
  '/tools': typeof ToolsIndexRoute
  '/api/clearance/a2a': typeof ApiClearanceA2aRoute
  '/api/clearance/account': typeof ApiClearanceAccountRoute
  '/api/clearance/audit': typeof ApiClearanceAuditRoute
  '/api/clearance/check': typeof ApiClearanceCheckRoute
  '/api/clearance/pay': typeof ApiClearancePayRoute
  '/api/clearance/permissions': typeof ApiClearancePermissionsRoute
  '/api/clearance/probe': typeof ApiClearanceProbeRoute
  '/api/clearance/session': typeof ApiClearanceSessionRoute
  '/api/clearance/status': typeof ApiClearanceStatusRoute
  '/api/clearance/tools': typeof ApiClearanceToolsRoute
  '/api/clearance/venice-eval': typeof ApiClearanceVeniceEvalRoute
  '/api/demo/x402': typeof ApiDemoX402Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/a2a-lab': typeof A2aLabRoute
  '/agent-clearance': typeof AgentClearanceRoute
  '/agent-demo': typeof AgentDemoRoute
  '/audit': typeof AuditRoute
  '/cli': typeof CliRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/payment-lab': typeof PaymentLabRoute
  '/permissions': typeof PermissionsRoute
  '/relayer': typeof RelayerRoute
  '/sdk': typeof SdkRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/tool-onboarding': typeof ToolOnboardingRoute
  '/venice-eval': typeof VeniceEvalRoute
  '/tools/$id': typeof ToolsIdRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/clearance/a2a': typeof ApiClearanceA2aRoute
  '/api/clearance/account': typeof ApiClearanceAccountRoute
  '/api/clearance/audit': typeof ApiClearanceAuditRoute
  '/api/clearance/check': typeof ApiClearanceCheckRoute
  '/api/clearance/pay': typeof ApiClearancePayRoute
  '/api/clearance/permissions': typeof ApiClearancePermissionsRoute
  '/api/clearance/probe': typeof ApiClearanceProbeRoute
  '/api/clearance/session': typeof ApiClearanceSessionRoute
  '/api/clearance/status': typeof ApiClearanceStatusRoute
  '/api/clearance/tools': typeof ApiClearanceToolsRoute
  '/api/clearance/venice-eval': typeof ApiClearanceVeniceEvalRoute
  '/api/demo/x402': typeof ApiDemoX402Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/a2a-lab'
    | '/agent-clearance'
    | '/agent-demo'
    | '/audit'
    | '/cli'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/mcp'
    | '/payment-lab'
    | '/permissions'
    | '/relayer'
    | '/sdk'
    | '/settings'
    | '/status'
    | '/tool-onboarding'
    | '/venice-eval'
    | '/tools/$id'
    | '/tools/'
    | '/api/clearance/a2a'
    | '/api/clearance/account'
    | '/api/clearance/audit'
    | '/api/clearance/check'
    | '/api/clearance/pay'
    | '/api/clearance/permissions'
    | '/api/clearance/probe'
    | '/api/clearance/session'
    | '/api/clearance/status'
    | '/api/clearance/tools'
    | '/api/clearance/venice-eval'
    | '/api/demo/x402'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/a2a-lab'
    | '/agent-clearance'
    | '/agent-demo'
    | '/audit'
    | '/cli'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/mcp'
    | '/payment-lab'
    | '/permissions'
    | '/relayer'
    | '/sdk'
    | '/settings'
    | '/status'
    | '/tool-onboarding'
    | '/venice-eval'
    | '/tools/$id'
    | '/tools'
    | '/api/clearance/a2a'
    | '/api/clearance/account'
    | '/api/clearance/audit'
    | '/api/clearance/check'
    | '/api/clearance/pay'
    | '/api/clearance/permissions'
    | '/api/clearance/probe'
    | '/api/clearance/session'
    | '/api/clearance/status'
    | '/api/clearance/tools'
    | '/api/clearance/venice-eval'
    | '/api/demo/x402'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/a2a-lab'
    | '/agent-clearance'
    | '/agent-demo'
    | '/audit'
    | '/cli'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/mcp'
    | '/payment-lab'
    | '/permissions'
    | '/relayer'
    | '/sdk'
    | '/settings'
    | '/status'
    | '/tool-onboarding'
    | '/venice-eval'
    | '/tools/$id'
    | '/tools/'
    | '/api/clearance/a2a'
    | '/api/clearance/account'
    | '/api/clearance/audit'
    | '/api/clearance/check'
    | '/api/clearance/pay'
    | '/api/clearance/permissions'
    | '/api/clearance/probe'
    | '/api/clearance/session'
    | '/api/clearance/status'
    | '/api/clearance/tools'
    | '/api/clearance/venice-eval'
    | '/api/demo/x402'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  A2aLabRoute: typeof A2aLabRoute
  AgentClearanceRoute: typeof AgentClearanceRoute
  AgentDemoRoute: typeof AgentDemoRoute
  AuditRoute: typeof AuditRoute
  CliRoute: typeof CliRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PaymentLabRoute: typeof PaymentLabRoute
  PermissionsRoute: typeof PermissionsRoute
  RelayerRoute: typeof RelayerRoute
  SdkRoute: typeof SdkRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  ToolOnboardingRoute: typeof ToolOnboardingRoute
  VeniceEvalRoute: typeof VeniceEvalRoute
  ToolsIdRoute: typeof ToolsIdRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  ApiClearanceA2aRoute: typeof ApiClearanceA2aRoute
  ApiClearanceAccountRoute: typeof ApiClearanceAccountRoute
  ApiClearanceAuditRoute: typeof ApiClearanceAuditRoute
  ApiClearanceCheckRoute: typeof ApiClearanceCheckRoute
  ApiClearancePayRoute: typeof ApiClearancePayRoute
  ApiClearancePermissionsRoute: typeof ApiClearancePermissionsRoute
  ApiClearanceProbeRoute: typeof ApiClearanceProbeRoute
  ApiClearanceSessionRoute: typeof ApiClearanceSessionRoute
  ApiClearanceStatusRoute: typeof ApiClearanceStatusRoute
  ApiClearanceToolsRoute: typeof ApiClearanceToolsRoute
  ApiClearanceVeniceEvalRoute: typeof ApiClearanceVeniceEvalRoute
  ApiDemoX402Route: typeof ApiDemoX402Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venice-eval': {
      id: '/venice-eval'
      path: '/venice-eval'
      fullPath: '/venice-eval'
      preLoaderRoute: typeof VeniceEvalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool-onboarding': {
      id: '/tool-onboarding'
      path: '/tool-onboarding'
      fullPath: '/tool-onboarding'
      preLoaderRoute: typeof ToolOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdk': {
      id: '/sdk'
      path: '/sdk'
      fullPath: '/sdk'
      preLoaderRoute: typeof SdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relayer': {
      id: '/relayer'
      path: '/relayer'
      fullPath: '/relayer'
      preLoaderRoute: typeof RelayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-lab': {
      id: '/payment-lab'
      path: '/payment-lab'
      fullPath: '/payment-lab'
      preLoaderRoute: typeof PaymentLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-demo': {
      id: '/agent-demo'
      path: '/agent-demo'
      fullPath: '/agent-demo'
      preLoaderRoute: typeof AgentDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-clearance': {
      id: '/agent-clearance'
      path: '/agent-clearance'
      fullPath: '/agent-clearance'
      preLoaderRoute: typeof AgentClearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a2a-lab': {
      id: '/a2a-lab'
      path: '/a2a-lab'
      fullPath: '/a2a-lab'
      preLoaderRoute: typeof A2aLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$id': {
      id: '/tools/$id'
      path: '/tools/$id'
      fullPath: '/tools/$id'
      preLoaderRoute: typeof ToolsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/x402': {
      id: '/api/demo/x402'
      path: '/api/demo/x402'
      fullPath: '/api/demo/x402'
      preLoaderRoute: typeof ApiDemoX402RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clearance/venice-eval': {
      id: '/api/clearance/venice-eval'
      path: '/api/clearance/venice-eval'
      fullPath: '/api/clearance/venice-eval'
      preLoaderRoute: typeof ApiClearanceVeniceEvalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clearance/tools': {
      id: '/api/clearance/tools'
      path: '/api/clearance/tools'
      fullPath: '/api/clearance/tools'
      preLoaderRoute: typeof ApiClearanceToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clearance/status': {
      id: '/api/clearance/status'
      path: '/api/clearance/status'
      fullPath: '/api/clearance/status'
      preLoaderRoute: typeof ApiClearanceStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clearance/session': {
      id: '/api/clearance/session'
      path: '/api/clearance/session'
      fullPath: '/api/clearance/session'
      preLoaderRoute: typeof ApiClearanceSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clearance/probe': {
      id: '/api/clearance/probe'
      path: '/api/clearance/probe'
      fullPath: '/api/clearance/probe'
      preLoaderRoute: typeof ApiClearanceProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clearance/permissions': {
      id: '/api/clearance/permissions'
      path: '/api/clearance/permissions'
      fullPath: '/api/clearance/permissions'
      preLoaderRoute: typeof ApiClearancePermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clearance/pay': {
      id: '/api/clearance/pay'
      path: '/api/clearance/pay'
      fullPath: '/api/clearance/pay'
      preLoaderRoute: typeof ApiClearancePayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clearance/check': {
      id: '/api/clearance/check'
      path: '/api/clearance/check'
      fullPath: '/api/clearance/check'
      preLoaderRoute: typeof ApiClearanceCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clearance/audit': {
      id: '/api/clearance/audit'
      path: '/api/clearance/audit'
      fullPath: '/api/clearance/audit'
      preLoaderRoute: typeof ApiClearanceAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clearance/account': {
      id: '/api/clearance/account'
      path: '/api/clearance/account'
      fullPath: '/api/clearance/account'
      preLoaderRoute: typeof ApiClearanceAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clearance/a2a': {
      id: '/api/clearance/a2a'
      path: '/api/clearance/a2a'
      fullPath: '/api/clearance/a2a'
      preLoaderRoute: typeof ApiClearanceA2aRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  A2aLabRoute: A2aLabRoute,
  AgentClearanceRoute: AgentClearanceRoute,
  AgentDemoRoute: AgentDemoRoute,
  AuditRoute: AuditRoute,
  CliRoute: CliRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PaymentLabRoute: PaymentLabRoute,
  PermissionsRoute: PermissionsRoute,
  RelayerRoute: RelayerRoute,
  SdkRoute: SdkRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  ToolOnboardingRoute: ToolOnboardingRoute,
  VeniceEvalRoute: VeniceEvalRoute,
  ToolsIdRoute: ToolsIdRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  ApiClearanceA2aRoute: ApiClearanceA2aRoute,
  ApiClearanceAccountRoute: ApiClearanceAccountRoute,
  ApiClearanceAuditRoute: ApiClearanceAuditRoute,
  ApiClearanceCheckRoute: ApiClearanceCheckRoute,
  ApiClearancePayRoute: ApiClearancePayRoute,
  ApiClearancePermissionsRoute: ApiClearancePermissionsRoute,
  ApiClearanceProbeRoute: ApiClearanceProbeRoute,
  ApiClearanceSessionRoute: ApiClearanceSessionRoute,
  ApiClearanceStatusRoute: ApiClearanceStatusRoute,
  ApiClearanceToolsRoute: ApiClearanceToolsRoute,
  ApiClearanceVeniceEvalRoute: ApiClearanceVeniceEvalRoute,
  ApiDemoX402Route: ApiDemoX402Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
